### ISSUE TITLE
mac install failed

### ISSUE THREAD

**Issue by crisprss** [W01fh4cker/VcenterKit#5]
已经安装qt，但是报错

qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by W01fh4cker** [comment]
百度得以下文章，可以尝试：
`https://juejin.cn/s/could%20not%20find%20the%20qt%20platform%20plugin%20windows%20in%20python`、
`https://blog.51cto.com/u_15906863/5977698`，我手边没有mac环境。

**Comment by crisprss** [comment]
重新安装qt5，已经解决，感谢
