### ISSUE TITLE
师傅我运行vcenterkit界面为啥这么紧凑呀调整不了大小。。

### ISSUE THREAD

**Issue by iScriptKid** [W01fh4cker/VcenterKit#7]
![1698816324535](https://github.com/W01fh4cker/VcenterKit/assets/51255283/711d0696-058d-436b-bff2-992d3e588e85)

**Comment by W01fh4cker** [comment]
原`ui`文件被我误删了，这段时间我也很忙，就没更新了。你试试看下载exe文件打开试试看呢？  
下载地址：https://github.com/W01fh4cker/VcenterKit/releases/download/v0.0.2/VcenterKit-v0.02.zip
